version: '3.1'
services:
  app:
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./FlaskDockerFile
    links:
      - db
    ports:
      - 80:5000

  db:
    image: mysql:5.7
    ports:
      - 33061:3306
    environment:
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - ./db/:/docker-entrypoint-initdb.d/:ro
